### ISSUE TITLE
Test has started to fail with recent Dist-Zilla-Plugin-ModuleBuildTiny

### ISSUE THREAD

**Issue by andk** [Perl5-FFI/Dist-Zilla-Plugin-FFI#12]
The following two test reports for Dist-Zilla-Plugin-FFI-1.07 were sent in short succession and in between I did nothing but install LEONT/Dist-Zilla-Plugin-ModuleBuildTiny-0.016.tar.gz:

- pass: http://www.cpantesters.org/cpan/report/3eea1510-ec3f-11ed-9faf-de36709e9f2a
- fail: http://www.cpantesters.org/cpan/report/f1f644e4-ec3f-11ed-a897-f040709e9f2a

@leont, would you like to chime in?

**Comment by Leont** [comment]
Apparently it's very sensitive to the whitespace in the generated Build.PL. This approach is generally fragile.

I think I could fix this by adding an extra newline, but I'm wondering if we can't do better by making most of this dist a role so it can be integrated into a subclass of `[ModuleBuildTiny]` or `[MakeMaker::Awesome]`

**Comment by plicease** [comment]
The `[CheckLib]` plugin has the same problem, since this code is based on that.

**Comment by plicease** [comment]
@karenetheridge

**Comment by plicease** [comment]
#13 is also an option.

**Comment by Leont** [comment]
This should be resolved with [Dist-Zilla-Plugin-ModuleBuildTiny-0.017](https://metacpan.org/release/LEONT/Dist-Zilla-Plugin-ModuleBuildTiny-0.017)

**Comment by plicease** [comment]
> This should be resolved with [Dist-Zilla-Plugin-ModuleBuildTiny-0.017](https://metacpan.org/release/LEONT/Dist-Zilla-Plugin-ModuleBuildTiny-0.017)

Verified this now works for me.
